# Generated by Django 2.0.5 on 2019-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactform',
            name='mobile_no',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
