# Generated by Django 2.0.5 on 2019-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_detection', '0002_auto_20190630_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
